#### Задание 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pylab import rcParams

%matplotlib inline
%config InlineBackend.figure_format='svg'

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Задание 2

In [3]:
b1 = np.random.choice(a, (3, 3))
b1

array([[14, 19, 14],
       [14, 15, 16],
       [14, 16, 20]])

In [5]:
b2 = a.reshape(3, 4)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
b3 = a.reshape(2, 6)
b3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
b4 = a.reshape(6, 2)
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [17]:
b5 = a.reshape(4, 3)
b5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### Задание 3

In [21]:
c1 = a.reshape(-1, 2)
c1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [22]:
c2 = a.reshape(-1, 3)
c2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
c3 = a.reshape(2, -1)
c3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
c4 = a.reshape(3, -1)
c4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
c5 = a.reshape(12, -1)
c5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Задание 5

In [30]:
x = np.round(np.random.randn(3, 4) * 10, 4)
x

array([[  2.0886, -19.5967, -13.2819,   1.9686],
       [  7.3847,   1.7137,  -1.1565,  -3.011 ],
       [-14.7852,  -7.1984,  -4.6064,  10.5712]])

In [31]:
y = x.flatten()
y

array([  2.0886, -19.5967, -13.2819,   1.9686,   7.3847,   1.7137,
        -1.1565,  -3.011 , -14.7852,  -7.1984,  -4.6064,  10.5712])

In [34]:
y.shape

(12,)

#### Задание 6

In [38]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Задание 7

In [36]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Задание 8

In [39]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [40]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
v.size

10

#### Задание 9

In [44]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [49]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

#### Задание 10. Инициализация генератора случ чисел, равного 42

In [51]:
np.random.seed(42)

#### Задание 11

In [54]:
c = np.arange(0, 16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Задание 12

In [57]:
C = c.reshape(4, 4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
D = B + (C*10)
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

Определитель матрицы D

In [59]:
np.linalg.det(D)

5.18953807259442e-26

Ранг матрицы D

In [61]:
np.linalg.matrix_rank(D)

2

In [62]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

#### Задание 13

In [81]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [82]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [83]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])